"""baseline schema

Revision ID: 0001
Revises: 
Create Date: 2026-10-06 11:26:33.333664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_analytics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=True),
    sa.Column('message_count', sa.Integer(), nullable=True),
    sa.Column('topic', sa.String(length=100), nullable=True),
    sa.Column('timestamp', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_analytics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_analytics_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_analytics_user_id'), ['user_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('preferred_language', sa.String(length=10), nullable=True),
    sa.Column('subscription_tier', sa.String(length=20), nullable=True),
    sa.Column('daily_translation_seconds_used', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.Float(), nullable=True),
    sa.Column('token_version', sa.Integer(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_phone'), ['phone'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_user_id'), ['user_id'], unique=True)

    op.create_table('activity_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('xp_earned', sa.Integer(), server_default='0', nullable=True),
    sa.Column('timestamp', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activity_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activity_log_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_log_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_log_user_id'), ['user_id'], unique=False)

    op.create_table('chat_messages',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('sender_id', sa.String(length=50), nullable=True),
    sa.Column('receiver_id', sa.String(length=50), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=True),
    sa.Column('timestamp', sa.Float(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['receiver_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_messages_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_messages_receiver_id'), ['receiver_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_messages_sender_id'), ['sender_id'], unique=False)

    op.create_table('community_posts',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=True),
    sa.Column('user_name', sa.String(length=100), nullable=False),
    sa.Column('avatar_initials', sa.String(length=10), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('comments_count', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.Float(), nullable=True),
    sa.Column('is_official', sa.Boolean(), nullable=True),
    sa.Column('achievement_text', sa.String(length=200), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('community_posts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_community_posts_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_community_posts_user_id'), ['user_id'], unique=False)

    op.create_table('game_session_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=True),
    sa.Column('game_id', sa.String(length=50), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('words_completed', sa.Integer(), nullable=True),
    sa.Column('total_attempts', sa.Integer(), nullable=True),
    sa.Column('best_streak', sa.Integer(), nullable=True),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('played_at', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('game_session_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_game_session_history_id'), ['id'], unique=False)

    op.create_table('learning_precision',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=True),
    sa.Column('word', sa.String(length=50), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=True),
    sa.Column('correct_count', sa.Integer(), nullable=True),
    sa.Column('best_confidence', sa.Float(), nullable=True),
    sa.Column('proficiency', sa.Float(), nullable=True),
    sa.Column('last_attempt_time', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('learning_precision', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_learning_precision_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_learning_precision_word'), ['word'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('timestamp', sa.Float(), nullable=True),
    sa.Column('action_url', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)

    op.create_table('user_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=True),
    sa.Column('theme', sa.String(length=20), nullable=True),
    sa.Column('notifications_enabled', sa.Boolean(), nullable=True),
    sa.Column('sound_enabled', sa.Boolean(), nullable=True),
    sa.Column('daily_goal_minutes', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_settings_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_settings_user_id'), ['user_id'], unique=True)

    op.create_table('user_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=True),
    sa.Column('total_xp', sa.Integer(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('games_played', sa.Integer(), nullable=True),
    sa.Column('best_score', sa.Integer(), nullable=True),
    sa.Column('best_game_score', sa.Integer(), nullable=True),
    sa.Column('unlocked_achievements', sa.JSON(), nullable=True),
    sa.Column('current_streak', sa.Integer(), server_default='0', nullable=True),
    sa.Column('longest_streak', sa.Integer(), server_default='0', nullable=True),
    sa.Column('last_active_date', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    with op.batch_alter_table('user_stats', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_stats_id'), ['id'], unique=False)

    op.create_table('community_comments',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('post_id', sa.String(length=50), nullable=True),
    sa.Column('user_id', sa.String(length=50), nullable=True),
    sa.Column('user_name', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['community_posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('community_comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_community_comments_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_community_comments_post_id'), ['post_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_community_comments_user_id'), ['user_id'], unique=False)

    op.create_table('community_post_likes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('timestamp', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['community_posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id', 'user_id', name='uq_post_like')
    )
    with op.batch_alter_table('community_post_likes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_community_post_likes_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_community_post_likes_post_id'), ['post_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_community_post_likes_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('community_post_likes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_community_post_likes_user_id'))
        batch_op.drop_index(batch_op.f('ix_community_post_likes_post_id'))
        batch_op.drop_index(batch_op.f('ix_community_post_likes_id'))

    op.drop_table('community_post_likes')
    with op.batch_alter_table('community_comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_community_comments_user_id'))
        batch_op.drop_index(batch_op.f('ix_community_comments_post_id'))
        batch_op.drop_index(batch_op.f('ix_community_comments_id'))

    op.drop_table('community_comments')
    with op.batch_alter_table('user_stats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_stats_id'))

    op.drop_table('user_stats')
    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_settings_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_settings_id'))

    op.drop_table('user_settings')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_id'))

    op.drop_table('notifications')
    with op.batch_alter_table('learning_precision', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_learning_precision_word'))
        batch_op.drop_index(batch_op.f('ix_learning_precision_id'))

    op.drop_table('learning_precision')
    with op.batch_alter_table('game_session_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_game_session_history_id'))

    op.drop_table('game_session_history')
    with op.batch_alter_table('community_posts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_community_posts_user_id'))
        batch_op.drop_index(batch_op.f('ix_community_posts_id'))

    op.drop_table('community_posts')
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_messages_sender_id'))
        batch_op.drop_index(batch_op.f('ix_chat_messages_receiver_id'))
        batch_op.drop_index(batch_op.f('ix_chat_messages_id'))

    op.drop_table('chat_messages')
    with op.batch_alter_table('activity_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_log_user_id'))
        batch_op.drop_index(batch_op.f('ix_activity_log_timestamp'))
        batch_op.drop_index(batch_op.f('ix_activity_log_id'))

    op.drop_table('activity_log')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_user_id'))
        batch_op.drop_index(batch_op.f('ix_users_phone'))
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('chat_analytics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_analytics_user_id'))
        batch_op.drop_index(batch_op.f('ix_chat_analytics_id'))

    op.drop_table('chat_analytics')
    # ### end Alembic commands ###
